name: csafe_fitness
description: A dart implementation of the CSAFE protocol framework for fitness machines
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
